services:
  postgres:
    image: postgres:17
    container_name: massplanner_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: massplanner
    ports:
      - "5432:5432"
